# Generated by Django 3.0.4 on 2020-03-24 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('limit', models.IntegerField(help_text='Persons limit', validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.CharField(help_text='Follows the format "0001", "0002", etc...', max_length=4, unique=True)),
                ('m2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, help_text='Per day', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
